import json
import os
import base64

# Load and encode pipeline diagram to base64 for 100% self-contained offline rendering
img_file_path = "/home/aks1/drone_course_repo/tutorials/single_integrator_pipeline.png"
with open(img_file_path, "rb") as f:
    pipeline_b64 = base64.b64encode(f.read()).decode("utf-8")

img_tag = f"<p align=\"center\"><img src=\"data:image/png;base64,{pipeline_b64}\" width=\"100%\" alt=\"6-DOF Quadrotor Control Pipeline: Single-Integrator with Black-Box Controller in MuJoCo\" /></p>\n"

notebook = {
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {
        "colab": {
            "provenance": [],
            "authorship_tag": "ABX9TyP...",
            "include_colab_link": True
        },
        "kernelspec": {
            "name": "python3",
            "display_name": "Python 3"
        },
        "language_info": {
            "name": "python"
        },
        "accelerator": "GPU"
    },
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {"id": "header_md"},
            "source": [
                "# 🛡️ Perception and Control for Drones: Control Barrier Function (CBF) Safety Filter Tutorial\n",
                "\n",
                "[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/arunkumar-singh/drone_course_repo/blob/main/tutorials/quadrotor_cbf_safety_filter_colab.ipynb)\n",
                "\n",
                "Welcome to this hands-on tutorial on **Control Barrier Functions (CBFs)** and **Safety Filters (SF)** for autonomous quadrotor flight in **Google Colab** using **Gymnasium** and **MuJoCo**.\n",
                "\n",
                "### Motivation: Why Standard PID Fails in Cluttered Environments\n",
                "In classical drone navigation, a high-level **Position PID Controller** generates velocity commands directed straight towards a target waypoint. However, if an obstacle lies along the path, the unconstrained PID controller will drive the drone **directly into the obstacle**, causing a catastrophic crash.\n",
                "\n",
                "### The Two-Tier Architecture with CBF Safety Filter\n",
                "Rather than replacing the proven goal-reaching PID controller, modern safety-critical robotics introduces a **Control Barrier Function (CBF) Safety Filter (SF)**:\n",
                "- **Tier 1 (Guidance)**: Goal-reaching PID controller computes nominal desired velocity $\\mathbf{v}_{\\mathrm{des}}$.\n",
                "- **Safety Filter**: Intercepts $\\mathbf{v}_{\\mathrm{des}}$ and minimally modifies it into a guaranteed safe command $\\mathbf{v}^*$ that satisfies forward invariance of the obstacle-free set $\\mathcal{S}$.\n",
                "- **Tier 2 (Black-Box Lower-Level Controller)**: Translates $\\mathbf{v}^*$ into motor thrusts via tilt kinematics and analytical mixer inversion.\n",
                "\n",
                img_tag,
                "\n",
                "### Theoretical Foundation (Based on Ames et al., *Control Barrier Functions for Collision Avoidance on Quadrotors*)\n",
                "For single-integrator dynamics $\\mathbf{\\dot{p}} = \\mathbf{v}$, an obstacle at $\\mathbf{p}_{\\mathrm{obs}}$ with safety radius $D_{\\mathrm{obs}}$ defines the barrier function:\n",
                "$$h(\\mathbf{p}) = \\|\\mathbf{p} - \\mathbf{p}_{\\mathrm{obs}}\\| - D_{\\mathrm{obs}}$$\n",
                "The safe set is $\\mathcal{S} = \\{\\mathbf{p} \\in \\mathbb{R}^3 : h(\\mathbf{p}) \\ge 0\\}$. By **Theorem 1**, forward invariance is guaranteed if:\n",
                "$$\\dot{h}(\\mathbf{p}, \\mathbf{v}) = \\nabla h(\\mathbf{p})^T \\mathbf{v} \\ge -\\alpha h(\\mathbf{p}), \\quad \\alpha > 0$$\n",
                "\n",
                "The **CBF-QP Safety Filter** solves:\n",
                "$$\\mathbf{v}^* = \\arg\\min_{\\mathbf{v}} \\frac{1}{2} \\|\\mathbf{v} - \\mathbf{v}_{\\mathrm{des}}\\|^2 \\quad \\text{s.t.} \\quad \\nabla h(\\mathbf{p})^T \\mathbf{v} \\ge -\\alpha h(\\mathbf{p})$$\n",
                "\n",
                "As derived in Eq. (15)-(16) & (19) of the paper, this QP has an **exact closed-form solution**:\n",
                "$$\\Psi(\\mathbf{p}; \\mathbf{v}_{\\mathrm{des}}) = \\nabla h(\\mathbf{p})^T \\mathbf{v}_{\\mathrm{des}} + \\alpha h(\\mathbf{p})$$\n",
                "$$\\mathbf{v}^* = \\begin{cases} \\mathbf{v}_{\\mathrm{des}} - \\Psi(\\mathbf{p}; \\mathbf{v}_{\\mathrm{des}}) \\nabla h(\\mathbf{p}) & \\text{if } \\Psi < 0 \\\\ \\mathbf{v}_{\\mathrm{des}} & \\text{if } \\Psi \\ge 0 \\end{cases}$$\n",
                "\n",
                "### In This Tutorial, You Will Learn:\n",
                "1. **EGL Headless Setup**: Running hardware-accelerated OpenGL in Google Colab.\n",
                "2. **MuJoCo 3D Obstacle Environment**: Embedding physical collision spheres in MJCF.\n",
                "3. **Single-Integrator CBF Safety Filter**: Implementing the closed-form barrier projection in pure NumPy.\n",
                "4. **Comparative Experiment**: Flying an unconstrained PID straight into the obstacle vs. the CBF filter deflecting smoothly around it.\n",
                "5. **Telemetry & Visual Proof**: Plotting barrier values $h(t) \\ge 0$, clearance distances, and rendering in-notebook HD flight videos."
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {"id": "sec1_md"},
            "source": [
                "## 1. Install Dependencies & Configure Headless OpenGL\n",
                "\n",
                "We configure MuJoCo to use **EGL** (`MUJOCO_GL=\"egl\"`) for hardware-accelerated offscreen rendering in Google Colab without requiring an X11 display."
            ]
        },
        {
            "cell_type": "code",
            "metadata": {"id": "install_deps"},
            "execution_count": None,
            "outputs": [],
            "source": [
                "# 1. Configure MuJoCo for headless GPU rendering (EGL) in Google Colab\n",
                "import os\n",
                "os.environ[\"MUJOCO_GL\"] = \"egl\"\n",
                "\n",
                "# 2. Install required packages\n",
                "!pip install -q gymnasium mujoco mediapy matplotlib scipy\n",
                "\n",
                "# 3. Bind EGL GLContext to MuJoCo\n",
                "import mujoco\n",
                "try:\n",
                "    import mujoco.egl\n",
                "    mujoco.GLContext = mujoco.egl.GLContext\n",
                "except Exception:\n",
                "    pass\n",
                "\n",
                "import numpy as np\n",
                "import gymnasium as gym\n",
                "from gymnasium import spaces\n",
                "import mediapy as media\n",
                "import matplotlib.pyplot as plt\n",
                "\n",
                "print(f\"MuJoCo Version:         {mujoco.__version__}\")\n",
                "print(f\"Active OpenGL Platform: {getattr(mujoco, 'GLContext', 'Default')}\")\n",
                "print(f\"Gymnasium Version:      {gym.__version__}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {"id": "sec2_md"},
            "source": [
                "## 2. The 6-DOF Quadrotor Model with 3D Obstacles (MJCF XML)\n",
                "\n",
                "We define the quadrotor simulation in MuJoCo XML format:\n",
                "- **Freejoint root**: Full 6-DOF rigid-body dynamics (mass $m = 0.500\\text{ kg}$)\n",
                "- **Physical Spherical Obstacle**: Placed at $[0.6, 0.6, 1.35]$ with radius $0.22\\text{ m}$ in crimson red\n",
                "- **Mocap Target Sphere**: Visual golden sphere indicating the current 3D goal waypoint\n",
                "- **Cameras**: Third-person chase camera (`track_cam`) and wide arena observer (`arena_cam`)"
            ]
        },
        {
            "cell_type": "code",
            "metadata": {"id": "define_xml"},
            "execution_count": None,
            "outputs": [],
            "source": [
                "QUADROTOR_XML = \"\"\"\n",
                "<mujoco model=\"quadrotor\">\n",
                "  <compiler angle=\"radian\" coordinate=\"local\"/>\n",
                "  <option gravity=\"0 0 -9.81\" integrator=\"RK4\" timestep=\"0.01\"/>\n",
                "\n",
                "  <visual>\n",
                "    <headlight ambient=\"0.4 0.4 0.4\" diffuse=\"0.8 0.8 0.8\" specular=\"0.1 0.1 0.1\"/>\n",
                "    <rgba haze=\"0.15 0.25 0.35 1\"/>\n",
                "    <global azimuth=\"120\" elevation=\"-20\" offwidth=\"1280\" offheight=\"720\"/>\n",
                "  </visual>\n",
                "\n",
                "  <asset>\n",
                "    <texture type=\"skybox\" builtin=\"gradient\" rgb1=\"0.3 0.5 0.7\" rgb2=\"0.0 0.1 0.2\" width=\"512\" height=\"512\"/>\n",
                "    <texture name=\"grid\" type=\"2d\" builtin=\"checker\" width=\"512\" height=\"512\" rgb1=\"0.25 0.35 0.45\" rgb2=\"0.15 0.2 0.25\"/>\n",
                "    <material name=\"grid\" texture=\"grid\" texrepeat=\"2 2\" texuniform=\"true\" reflectance=\"0.2\"/>\n",
                "    <material name=\"chassis\" rgba=\"0.15 0.15 0.15 1.0\" specular=\"0.5\" shininess=\"0.5\"/>\n",
                "    <material name=\"arm\" rgba=\"0.25 0.25 0.25 1.0\"/>\n",
                "    <material name=\"front_prop\" rgba=\"0.95 0.15 0.15 0.85\" specular=\"0.4\"/>\n",
                "    <material name=\"rear_prop\" rgba=\"0.15 0.45 0.95 0.85\" specular=\"0.4\"/>\n",
                "    <material name=\"target_mat\" rgba=\"1.0 0.8 0.0 0.85\" specular=\"0.9\"/>\n",
                "    <material name=\"obs_mat\" rgba=\"0.90 0.20 0.20 0.85\" specular=\"0.6\" shininess=\"0.4\"/>\n",
                "  </asset>\n",
                "\n",
                "  <worldbody>\n",
                "    <light directional=\"true\" diffuse=\"0.8 0.8 0.8\" specular=\"0.3 0.3 0.3\" pos=\"0 0 6.0\" dir=\"0 0 -1\"/>\n",
                "    <light directional=\"true\" diffuse=\"0.4 0.4 0.4\" specular=\"0.1 0.1 0.1\" pos=\"4 -4 5.0\" dir=\"-1 1 -1\"/>\n",
                "    <geom name=\"floor\" type=\"plane\" size=\"14 14 0.1\" material=\"grid\" condim=\"3\"/>\n",
                "\n",
                "    <!-- Target Waypoint Sphere (Mocap Body) -->\n",
                "    <body name=\"target\" pos=\"1.2 1.2 1.6\" mocap=\"true\">\n",
                "      <geom name=\"target_sphere\" type=\"sphere\" size=\"0.08\" material=\"target_mat\" contype=\"0\" conaffinity=\"0\" density=\"0\"/>\n",
                "    </body>\n",
                "\n",
                "    <!-- Static Obstacle Sphere (Positioned directly between start and goal) -->\n",
                "    <body name=\"obstacle1\" pos=\"0.6 0.6 1.35\">\n",
                "      <geom name=\"obs1_geom\" type=\"sphere\" size=\"0.22\" material=\"obs_mat\" contype=\"1\" conaffinity=\"1\"/>\n",
                "    </body>\n",
                "\n",
                "    <!-- Observer Cameras -->\n",
                "    <camera name=\"arena_cam\" pos=\"-1.0 -3.0 3.2\" xyaxes=\"1.0 0.0 0.0 0.0 0.6 0.8\" mode=\"fixed\"/>\n",
                "\n",
                "    <!-- 6-DOF Quadrotor Body -->\n",
                "    <body name=\"quadrotor\" pos=\"0 0 1.0\">\n",
                "      <freejoint name=\"root\"/>\n",
                "      <geom name=\"core\" type=\"box\" size=\"0.06 0.06 0.025\" material=\"chassis\" mass=\"0.26\"/>\n",
                "\n",
                "      <!-- X-Frame Diagonal Arms -->\n",
                "      <geom name=\"arm_0_2\" type=\"capsule\" fromto=\"-0.12 -0.12 0.0 0.12 0.12 0.0\" size=\"0.008\" material=\"arm\" mass=\"0.06\"/>\n",
                "      <geom name=\"arm_1_3\" type=\"capsule\" fromto=\"-0.12 0.12 0.0 0.12 -0.12 0.0\" size=\"0.008\" material=\"arm\" mass=\"0.06\"/>\n",
                "\n",
                "      <!-- Propeller Visual Geoms -->\n",
                "      <geom name=\"prop_0\" type=\"cylinder\" pos=\"0.12 0.12 0.012\" size=\"0.045 0.004\" material=\"front_prop\" mass=\"0.03\"/>\n",
                "      <geom name=\"prop_1\" type=\"cylinder\" pos=\"0.12 -0.12 0.012\" size=\"0.045 0.004\" material=\"front_prop\" mass=\"0.03\"/>\n",
                "      <geom name=\"prop_2\" type=\"cylinder\" pos=\"-0.12 0.12 0.012\" size=\"0.045 0.004\" material=\"rear_prop\" mass=\"0.03\"/>\n",
                "      <geom name=\"prop_3\" type=\"cylinder\" pos=\"-0.12 -0.12 0.012\" size=\"0.045 0.004\" material=\"rear_prop\" mass=\"0.03\"/>\n",
                "\n",
                "      <!-- Thruster Site Actuators -->\n",
                "      <site name=\"thrust_0\" pos=\"0.12 0.12 0.012\" size=\"0.01\"/>\n",
                "      <site name=\"thrust_1\" pos=\"0.12 -0.12 0.012\" size=\"0.01\"/>\n",
                "      <site name=\"thrust_2\" pos=\"-0.12 0.12 0.012\" size=\"0.01\"/>\n",
                "      <site name=\"thrust_3\" pos=\"-0.12 -0.12 0.012\" size=\"0.01\"/>\n",
                "\n",
                "      <!-- Third-Person Follow Camera attached to Quadrotor -->\n",
                "      <camera name=\"track_cam\" pos=\"-1.2 -1.2 0.6\" xyaxes=\"1.0 -1.0 0.0 0.5 0.5 1.0\" mode=\"trackcom\"/>\n",
                "    </body>\n",
                "  </worldbody>\n",
                "\n",
                "  <actuator>\n",
                "    <general name=\"motor_0\" site=\"thrust_0\" gear=\"0 0 1 0 0 -0.016\" ctrlrange=\"-1.0 1.0\" ctrllimited=\"true\"/>\n",
                "    <general name=\"motor_1\" site=\"thrust_1\" gear=\"0 0 1 0 0 0.016\" ctrlrange=\"-1.0 1.0\" ctrllimited=\"true\"/>\n",
                "    <general name=\"motor_2\" site=\"thrust_2\" gear=\"0 0 1 0 0 0.016\" ctrlrange=\"-1.0 1.0\" ctrllimited=\"true\"/>\n",
                "    <general name=\"motor_3\" site=\"thrust_3\" gear=\"0 0 1 0 0 -0.016\" ctrlrange=\"-1.0 1.0\" ctrllimited=\"true\"/>\n",
                "  </actuator>\n",
                "</mujoco>\n",
                "\"\"\"\n",
                "\n",
                "print(\"QUADROTOR_XML with physical obstacle defined successfully!\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {"id": "sec3_md"},
            "source": [
                "## 3. Base Gymnasium Environment (`QuadrotorEnv`)\n",
                "\n",
                "The base environment implements standard Gymnasium methods (`reset()`, `step()`, `render()`)."
            ]
        },
        {
            "cell_type": "code",
            "metadata": {"id": "env_class"},
            "execution_count": None,
            "outputs": [],
            "source": [
                "class QuadrotorEnv(gym.Env):\n",
                "    \"\"\"\n",
                "    Gymnasium Environment for a 6-DOF Quadrotor in MuJoCo.\n",
                "    \"\"\"\n",
                "    metadata = {\"render_modes\": [\"rgb_array\"], \"render_fps\": 50}\n",
                "\n",
                "    def __init__(self, xml_string=QUADROTOR_XML, target_pos=np.array([1.2, 1.2, 1.6]),\n",
                "                 camera_name=\"arena_cam\", max_steps=400):\n",
                "        super().__init__()\n",
                "        self.model = mujoco.MjModel.from_xml_string(xml_string)\n",
                "        self.data = mujoco.MjData(self.model)\n",
                "        self.target_pos = np.array(target_pos, dtype=np.float32)\n",
                "        self.camera_name = camera_name\n",
                "        self.max_steps = max_steps\n",
                "        self.current_step = 0\n",
                "\n",
                "        # 4 normalized motor inputs in [-1.0, 1.0]\n",
                "        self.action_space = spaces.Box(low=-1.0, high=1.0, shape=(4,), dtype=np.float32)\n",
                "        # 12-dim state: [pos(3), vel(3), roll_pitch_yaw(3), ang_vel(3)]\n",
                "        self.observation_space = spaces.Box(low=-np.inf, high=np.inf, shape=(12,), dtype=np.float32)\n",
                "\n",
                "        # Headless offscreen renderer\n",
                "        self.renderer = mujoco.Renderer(self.model, 540, 720)\n",
                "\n",
                "    def _quat_to_euler(self, q):\n",
                "        w, x, y, z = q\n",
                "        sinr_cosp = 2.0 * (w * x + y * z)\n",
                "        cosr_cosp = 1.0 - 2.0 * (x * x + y * y)\n",
                "        roll = np.arctan2(sinr_cosp, cosr_cosp)\n",
                "\n",
                "        sinp = 2.0 * (w * y - z * x)\n",
                "        pitch = np.arcsin(np.clip(sinp, -1.0, 1.0))\n",
                "\n",
                "        siny_cosp = 2.0 * (w * z + x * y)\n",
                "        cosy_cosp = 1.0 - 2.0 * (y * y + z * z)\n",
                "        yaw = np.arctan2(siny_cosp, cosy_cosp)\n",
                "        return np.array([roll, pitch, yaw], dtype=np.float32)\n",
                "\n",
                "    def _get_obs(self):\n",
                "        pos = self.data.qpos[0:3].copy()\n",
                "        quat = self.data.qpos[3:7].copy()\n",
                "        rpy = self._quat_to_euler(quat)\n",
                "        vel = self.data.qvel[0:3].copy()\n",
                "        ang_vel = self.data.qvel[3:6].copy()\n",
                "        return np.concatenate([pos, vel, rpy, ang_vel]).astype(np.float32)\n",
                "\n",
                "    def set_target_pos(self, target_pos):\n",
                "        self.target_pos = np.array(target_pos, dtype=np.float32)\n",
                "        target_body_id = mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_BODY, \"target\")\n",
                "        if target_body_id != -1:\n",
                "            mocap_id = self.model.body_mocapid[target_body_id]\n",
                "            if mocap_id != -1:\n",
                "                self.data.mocap_pos[mocap_id] = self.target_pos\n",
                "\n",
                "    def reset(self, seed=None, options=None):\n",
                "        super().reset(seed=seed)\n",
                "        mujoco.mj_resetData(self.model, self.data)\n",
                "        self.data.qpos[0:3] = np.array([0.0, 0.0, 1.0])\n",
                "        self.data.qpos[3:7] = np.array([1.0, 0.0, 0.0, 0.0])\n",
                "        self.set_target_pos(self.target_pos)\n",
                "        mujoco.mj_forward(self.model, self.data)\n",
                "        self.current_step = 0\n",
                "        return self._get_obs(), {}\n",
                "\n",
                "    def step(self, action):\n",
                "        self.data.ctrl[:] = np.clip(action, -1.0, 1.0)\n",
                "        for _ in range(2):\n",
                "            mujoco.mj_step(self.model, self.data)\n",
                "\n",
                "        self.current_step += 1\n",
                "        obs = self._get_obs()\n",
                "        pos = obs[0:3]\n",
                "        dist_to_target = np.linalg.norm(pos - self.target_pos)\n",
                "\n",
                "        reward = -dist_to_target\n",
                "        terminated = bool(pos[2] < 0.15 or abs(obs[6]) > 1.2 or abs(obs[7]) > 1.2)\n",
                "        truncated = bool(self.current_step >= self.max_steps)\n",
                "        return obs, reward, terminated, truncated, {\"dist_to_target\": dist_to_target}\n",
                "\n",
                "    def render(self):\n",
                "        self.renderer.update_scene(self.data, camera=self.camera_name)\n",
                "        return self.renderer.render().copy()\n",
                "\n",
                "    def close(self):\n",
                "        self.renderer.close()\n",
                "\n",
                "print(\"Base QuadrotorEnv created!\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {"id": "sec4_md"},
            "source": [
                "## 4. The Single-Integrator Abstraction & Black-Box Lower-Level Controller\n",
                "\n",
                "The `BlackBoxLowLevelController` handles tilt kinematics, attitude moments, tilt-compensated thrust, and motor mixing. It is wrapped by `SingleIntegratorQuadrotorEnv` so the guidance layer can send 3D velocity commands $\\mathbf{v}_{\\mathrm{cmd}} = [v_x, v_y, v_z]^T$."
            ]
        },
        {
            "cell_type": "code",
            "metadata": {"id": "blackbox_controller"},
            "execution_count": None,
            "outputs": [],
            "source": [
                "class BlackBoxLowLevelController:\n",
                "    \"\"\"\n",
                "    Deterministic Lower-Level Controller bridging Single-Integrator Velocity Commands\n",
                "    to 4-Motor MuJoCo Action Inputs.\n",
                "    \"\"\"\n",
                "    def __init__(self, mass=0.500, arm_length=0.17, max_thrust=3.8, c_tau=0.016):\n",
                "        self.mass = mass\n",
                "        self.d = arm_length * np.cos(np.pi / 4.0)\n",
                "        self.max_thrust = max_thrust\n",
                "        self.c_tau = c_tau\n",
                "        self.g = 9.81\n",
                "\n",
                "        # Velocity gains -> desired body accelerations\n",
                "        self.kv_xy = 3.5\n",
                "        self.kv_z  = 4.5\n",
                "\n",
                "        # Attitude restoration PD gains\n",
                "        self.kp_att = 0.35\n",
                "        self.kd_att = 0.045\n",
                "        self.kp_yaw = 0.12\n",
                "        self.kd_yaw = 0.025\n",
                "\n",
                "    def compute_motor_action(self, v_cmd, obs, yaw_des=0.0):\n",
                "        pos, vel, rpy, omega = obs[0:3], obs[3:6], obs[6:9], obs[9:12]\n",
                "        roll, pitch, yaw = rpy\n",
                "        p, q, r = omega\n",
                "\n",
                "        # 1. Commanded Accelerations in World Frame\n",
                "        a_cmd_world_x = self.kv_xy * (v_cmd[0] - vel[0])\n",
                "        a_cmd_world_y = self.kv_xy * (v_cmd[1] - vel[1])\n",
                "        a_cmd_world_z = self.kv_z  * (v_cmd[2] - vel[2])\n",
                "\n",
                "        # 2. Heading Rotation\n",
                "        cos_psi, sin_psi = np.cos(yaw), np.sin(yaw)\n",
                "        a_body_x =  cos_psi * a_cmd_world_x + sin_psi * a_cmd_world_y\n",
                "        a_body_y = -sin_psi * a_cmd_world_x + cos_psi * a_cmd_world_y\n",
                "\n",
                "        # 3. Kinematic Tilt Inversion\n",
                "        pitch_des = np.clip( a_body_x / self.g, -0.28, 0.28)\n",
                "        roll_des  = np.clip(-a_body_y / self.g, -0.28, 0.28)\n",
                "\n",
                "        # 4. Attitude Restoration Moments\n",
                "        yaw_err = np.arctan2(np.sin(yaw_des - yaw), np.cos(yaw_des - yaw))\n",
                "        tau_x = self.kp_att * (roll_des  - roll)  - self.kd_att * p\n",
                "        tau_y = self.kp_att * (pitch_des - pitch) - self.kd_att * q\n",
                "        tau_z = self.kp_yaw * yaw_err             - self.kd_yaw * r\n",
                "\n",
                "        # 5. Tilt-Compensated Collective Thrust\n",
                "        tilt_comp = max(0.65, np.cos(roll) * np.cos(pitch))\n",
                "        total_thrust = (self.mass * (self.g + a_cmd_world_z)) / tilt_comp\n",
                "        total_thrust = np.clip(total_thrust, 0.1 * self.mass * self.g, 1.95 * self.mass * self.g)\n",
                "\n",
                "        # 6. Exact Analytical Mixer Inversion\n",
                "        T_base = total_thrust / 4.0\n",
                "        dT_x   = tau_x / (4.0 * self.d)\n",
                "        dT_y   = tau_y / (4.0 * self.d)\n",
                "        dT_z   = tau_z / (4.0 * self.c_tau)\n",
                "\n",
                "        T0 = T_base + dT_x - dT_y + dT_z\n",
                "        T1 = T_base + dT_x + dT_y - dT_z\n",
                "        T2 = T_base - dT_x + dT_y + dT_z\n",
                "        T3 = T_base - dT_x - dT_y - dT_z\n",
                "\n",
                "        # 7. Normalize into [-1.0, 1.0] for MuJoCo\n",
                "        thrusts = np.clip([T0, T1, T2, T3], 0.0, self.max_thrust)\n",
                "        action = (thrusts / (0.5 * self.max_thrust)) - 1.0\n",
                "        return action.astype(np.float32)\n",
                "\n",
                "\n",
                "class SingleIntegratorQuadrotorEnv(gym.Wrapper):\n",
                "    \"\"\"\n",
                "    Gymnasium Wrapper abstracting the Quadrotor as a Single-Integrator:\n",
                "    Action: 3D Velocity Command v_cmd = [vx, vy, vz]\n",
                "    \"\"\"\n",
                "    def __init__(self, env, v_max=1.8):\n",
                "        super().__init__(env)\n",
                "        self.v_max = v_max\n",
                "        self.controller = BlackBoxLowLevelController()\n",
                "        self.action_space = spaces.Box(\n",
                "            low=-v_max, high=v_max, shape=(3,), dtype=np.float32\n",
                "        )\n",
                "\n",
                "    def set_target_pos(self, target_pos):\n",
                "        return self.env.set_target_pos(target_pos)\n",
                "\n",
                "    def step(self, v_cmd, yaw_des=0.0):\n",
                "        obs = self.env._get_obs()\n",
                "        v_cmd_clipped = np.clip(v_cmd, -self.v_max, self.v_max)\n",
                "        motor_action = self.controller.compute_motor_action(v_cmd_clipped, obs, yaw_des=yaw_des)\n",
                "        return self.env.step(motor_action)\n",
                "\n",
                "print(\"BlackBoxLowLevelController and SingleIntegratorQuadrotorEnv ready!\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {"id": "sec5_md"},
            "source": [
                "## 5. High-Level Goal-Reaching PID Controller\n",
                "\n",
                "The `HighLevelPositionPID` controller computes a nominal 3D velocity command directed towards a target waypoint:\n",
                "$$\\mathbf{v}_{\\mathrm{des}} = \\mathbf{K}_p \\mathbf{e} + \\mathbf{K}_i \\int \\mathbf{e}\\,d\\tau + \\mathbf{K}_d \\dot{\\mathbf{e}}$$\n",
                "Notice that this controller is completely unaware of obstacles."
            ]
        },
        {
            "cell_type": "code",
            "metadata": {"id": "highlevel_pid"},
            "execution_count": None,
            "outputs": [],
            "source": [
                "class HighLevelPositionPID:\n",
                "    \"\"\"\n",
                "    High-Level 3D Position PID Controller assuming Single-Integrator Dynamics (ṗ = v_cmd).\n",
                "    Computes nominal velocity commands [vx, vy, vz] to reach waypoints.\n",
                "    \"\"\"\n",
                "    def __init__(self, kp=2.2, ki=0.2, kd=0.4, v_max=1.8):\n",
                "        self.kp = kp\n",
                "        self.ki = ki\n",
                "        self.kd = kd\n",
                "        self.v_max = v_max\n",
                "        self.integral = np.zeros(3, dtype=np.float32)\n",
                "        self.prev_error = np.zeros(3, dtype=np.float32)\n",
                "\n",
                "    def reset(self):\n",
                "        self.integral = np.zeros(3, dtype=np.float32)\n",
                "        self.prev_error = np.zeros(3, dtype=np.float32)\n",
                "\n",
                "    def compute(self, current_pos, target_pos, dt=0.02):\n",
                "        error = np.array(target_pos, dtype=np.float32) - np.array(current_pos, dtype=np.float32)\n",
                "\n",
                "        # Conditional anti-windup\n",
                "        if np.linalg.norm(error) < 0.6:\n",
                "            self.integral = np.clip(self.integral + error * dt, -0.5, 0.5)\n",
                "\n",
                "        derivative = (error - self.prev_error) / dt\n",
                "        self.prev_error = error.copy()\n",
                "\n",
                "        v_des = self.kp * error + self.ki * self.integral + self.kd * derivative\n",
                "\n",
                "        speed = np.linalg.norm(v_des)\n",
                "        if speed > self.v_max:\n",
                "            v_des = v_des * (self.v_max / speed)\n",
                "\n",
                "        return v_des.astype(np.float32)\n",
                "\n",
                "print(\"HighLevelPositionPID controller implemented!\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {"id": "sec6_md"},
            "source": [
                "## 6. Control Barrier Function (CBF) Safety Filter\n",
                "\n",
                "Here we implement the **Single-Integrator CBF Safety Filter** from [`docs/cbf_drone.pdf`](https://github.com/arunkumar-singh/drone_course_repo/blob/main/docs/cbf_drone.pdf) (Theorem 1, Eq. 15-16 & 19).\n",
                "\n",
                "### Mathematical Details:\n",
                "1. **Barrier Function**: For obstacle center $\\mathbf{p}_{\\mathrm{obs}}$ and safe distance $D_{\\mathrm{obs}}$:\n",
                "   $$h(\\mathbf{p}) = \\|\\mathbf{p} - \\mathbf{p}_{\\mathrm{obs}}\\| - D_{\\mathrm{obs}}$$\n",
                "2. **Outward Normal Gradient**: $\\nabla h(\\mathbf{p}) = \\frac{\\mathbf{p} - \\mathbf{p}_{\\mathrm{obs}}}{\\|\\mathbf{p} - \\mathbf{p}_{\\mathrm{obs}}\\|}$ (unit vector, $\\|\\nabla h\\| = 1$)\n",
                "3. **Safety Margin Indicator**:\n",
                "   $$\\Psi(\\mathbf{p}; \\mathbf{v}_{\\mathrm{des}}) = \\nabla h(\\mathbf{p})^T \\mathbf{v}_{\\mathrm{des}} + \\alpha h(\\mathbf{p})$$\n",
                "4. **Closed-Form Safe Velocity**: (Eq. 16 & 19 of the paper):\n",
                "   $$\\mathbf{v}^* = \\begin{cases} \\mathbf{v}_{\\mathrm{des}} - \\Psi(\\mathbf{p}; \\mathbf{v}_{\\mathrm{des}}) \\nabla h(\\mathbf{p}) & \\text{if } \\Psi < 0 \\\\ \\mathbf{v}_{\\mathrm{des}} & \\text{if } \\Psi \\ge 0 \\end{cases}$$\n",
                "5. **Deadlock Resolution**: If the drone is directly head-on with the obstacle (collinear $\\nabla h \\parallel -\\mathbf{v}_{\\mathrm{des}}$), a tiny transverse circulation bias is injected to smoothly break the unstable equilibrium and guide the drone to circumvent the sphere."
            ]
        },
        {
            "cell_type": "code",
            "metadata": {"id": "cbf_safety_filter_class"},
            "execution_count": None,
            "outputs": [],
            "source": [
                "class CBFSafetyFilter:\n",
                "    \"\"\"\n",
                "    Control Barrier Function (CBF) Safety Filter for Single-Integrator Navigation.\n",
                "    Directly implements the pointwise optimal QP closed-form solution from docs/cbf_drone.pdf.\n",
                "    \"\"\"\n",
                "    def __init__(self, obstacles, D_obs=0.42, alpha=2.5, v_max=1.8):\n",
                "        \"\"\"\n",
                "        Parameters:\n",
                "            obstacles: List of 3D obstacle center positions [ [x, y, z], ... ]\n",
                "            D_obs: Safety buffer distance (obstacle radius + drone safety margin)\n",
                "            alpha: Class-K gain parameter (controls aggressiveness of the barrier boundary)\n",
                "            v_max: Maximum velocity limit (m/s)\n",
                "        \"\"\"\n",
                "        self.obstacles = [np.array(obs, dtype=np.float32) for obs in obstacles]\n",
                "        self.D_obs = D_obs\n",
                "        self.alpha = alpha\n",
                "        self.v_max = v_max\n",
                "\n",
                "    def filter(self, v_des, current_pos):\n",
                "        \"\"\"\n",
                "        Applies the CBF safety filter onto the nominal velocity v_des.\n",
                "        Returns:\n",
                "            v_safe: Filtered safe velocity command\n",
                "            min_h: Minimum barrier value across all obstacles\n",
                "            active_psi: Safety margin indicator for the most critical obstacle\n",
                "        \"\"\"\n",
                "        current_pos = np.array(current_pos, dtype=np.float32)\n",
                "        v_cmd = v_des.copy()\n",
                "\n",
                "        min_h = 999.0\n",
                "        active_psi = 999.0\n",
                "\n",
                "        # Evaluate barrier constraints across all obstacles\n",
                "        for p_obs in self.obstacles:\n",
                "            diff = current_pos - p_obs\n",
                "            dist = np.linalg.norm(diff)\n",
                "\n",
                "            if dist < 1e-4:\n",
                "                normal = np.array([1.0, 0.0, 0.0], dtype=np.float32)\n",
                "            else:\n",
                "                normal = diff / dist\n",
                "\n",
                "            # Barrier function value h(p)\n",
                "            h = dist - self.D_obs\n",
                "            if h < min_h:\n",
                "                min_h = h\n",
                "\n",
                "            # Safety margin Psi = ∇h^T v_des + alpha * h\n",
                "            psi = np.dot(normal, v_cmd) + self.alpha * h\n",
                "            if psi < active_psi:\n",
                "                active_psi = psi\n",
                "\n",
                "            # If safety constraint is violated, apply closed-form projection (Eq. 16 & 19)\n",
                "            if psi < 0.0:\n",
                "                # Analytical minimal-invasive correction\n",
                "                v_correction = -psi * normal\n",
                "                v_cmd = v_cmd + v_correction\n",
                "\n",
                "                # Circumvention Circulation: If approaching directly head-on, add a gentle\n",
                "                # transverse velocity component perpendicular to normal to prevent stalling\n",
                "                collinearity = abs(np.dot(normal, v_des) / (np.linalg.norm(v_des) + 1e-6))\n",
                "                if collinearity > 0.85 and h < 0.25:\n",
                "                    tangent = np.array([-normal[1], normal[0], 0.1], dtype=np.float32)\n",
                "                    norm_tangent = np.linalg.norm(tangent)\n",
                "                    if norm_tangent > 1e-4:\n",
                "                        tangent = tangent / norm_tangent\n",
                "                        v_cmd = v_cmd + 0.35 * tangent\n",
                "\n",
                "        # Enforce maximum speed saturation\n",
                "        speed = np.linalg.norm(v_cmd)\n",
                "        if speed > self.v_max:\n",
                "            v_cmd = v_cmd * (self.v_max / speed)\n",
                "\n",
                "        return v_cmd.astype(np.float32), min_h, active_psi\n",
                "\n",
                "print(\"CBFSafetyFilter class successfully defined!\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {"id": "sec7_md"},
            "source": [
                "## 7. Comparative Experiment: Unfiltered vs. CBF-Filtered Flight\n",
                "\n",
                "We conduct a direct head-to-head experiment:\n",
                "- **Start**: $[0.0, 0.0, 1.0]$\n",
                "- **Goal**: $[1.2, 1.2, 1.6]$\n",
                "- **Obstacle**: Positioned directly on the line of flight at $[0.6, 0.6, 1.35]$ with radius $R = 0.22\\text{ m}$ (safety threshold $D_{\\mathrm{obs}} = 0.42\\text{ m}$)\n",
                "\n",
                "1. **Run A (Unfiltered Nominal PID)**: Flies straight towards the goal and penetrates deep into the obstacle zone (collision!).\n",
                "2. **Run B (CBF Safety Filter Enabled)**: Detects the safety boundary $h(\\mathbf{p}) \\to 0$, activates safe projection, seamlessly circumnavigates the obstacle, and safely reaches the target."
            ]
        },
        {
            "cell_type": "code",
            "metadata": {"id": "comparative_experiment"},
            "execution_count": None,
            "outputs": [],
            "source": [
                "# =========================================================================\n",
                "# COMPARATIVE EXPERIMENT: UNFILTERED VS CBF-FILTERED FLIGHT\n",
                "# =========================================================================\n",
                "\n",
                "obs_center = np.array([0.6, 0.6, 1.35], dtype=np.float32)\n",
                "goal_pos = np.array([1.2, 1.2, 1.6], dtype=np.float32)\n",
                "D_obs = 0.42  # Safety distance (m)\n",
                "\n",
                "dt_ctrl = 0.02\n",
                "max_steps = 180\n",
                "\n",
                "# -------------------------------------------------------------------------\n",
                "# 1. Run A: Unfiltered Nominal PID\n",
                "# -------------------------------------------------------------------------\n",
                "print(\"=== Running Experiment A: Unfiltered Nominal PID ===\")\n",
                "base_env_a = QuadrotorEnv(target_pos=goal_pos, camera_name=\"arena_cam\", max_steps=max_steps)\n",
                "env_a = SingleIntegratorQuadrotorEnv(base_env_a, v_max=1.8)\n",
                "pid_a = HighLevelPositionPID(kp=2.2, ki=0.2, kd=0.4, v_max=1.8)\n",
                "\n",
                "obs_a, _ = env_a.reset(seed=42)\n",
                "frames_a = [env_a.render()]\n",
                "\n",
                "traj_a = []\n",
                "dists_a = []\n",
                "h_a = []\n",
                "v_cmds_a = []\n",
                "time_a = []\n",
                "\n",
                "t = 0.0\n",
                "for step in range(max_steps):\n",
                "    t += dt_ctrl\n",
                "    pos = obs_a[0:3]\n",
                "    d_obs = np.linalg.norm(pos - obs_center)\n",
                "    h_val = d_obs - D_obs\n",
                "\n",
                "    v_des = pid_a.compute(pos, goal_pos, dt=dt_ctrl)\n",
                "\n",
                "    traj_a.append(pos.copy())\n",
                "    dists_a.append(d_obs)\n",
                "    h_a.append(h_val)\n",
                "    v_cmds_a.append(v_des.copy())\n",
                "    time_a.append(t)\n",
                "\n",
                "    obs_a, _, terminated, truncated, _ = env_a.step(v_des)\n",
                "    frames_a.append(env_a.render())\n",
                "\n",
                "    if np.linalg.norm(pos - goal_pos) < 0.06:\n",
                "        break\n",
                "\n",
                "env_a.close()\n",
                "min_dist_a = min(dists_a)\n",
                "min_h_a = min(h_a)\n",
                "print(f\"Unfiltered Min Distance to Obstacle: {min_dist_a:.3f} m (Safety Threshold: {D_obs:.2f} m)\")\n",
                "print(f\"Unfiltered Min Barrier Value h(x):    {min_h_a:.3f} (CRASH: h < 0!)\\n\")\n",
                "\n",
                "# -------------------------------------------------------------------------\n",
                "# 2. Run B: CBF Safety Filter Enabled\n",
                "# -------------------------------------------------------------------------\n",
                "print(\"=== Running Experiment B: CBF Safety Filter Enabled ===\")\n",
                "base_env_b = QuadrotorEnv(target_pos=goal_pos, camera_name=\"arena_cam\", max_steps=max_steps)\n",
                "env_b = SingleIntegratorQuadrotorEnv(base_env_b, v_max=1.8)\n",
                "pid_b = HighLevelPositionPID(kp=2.2, ki=0.2, kd=0.4, v_max=1.8)\n",
                "cbf_filter = CBFSafetyFilter(obstacles=[obs_center], D_obs=D_obs, alpha=2.5, v_max=1.8)\n",
                "\n",
                "obs_b, _ = env_b.reset(seed=42)\n",
                "frames_b = [env_b.render()]\n",
                "\n",
                "traj_b = []\n",
                "dists_b = []\n",
                "h_b = []\n",
                "v_cmds_b = []\n",
                "v_nom_b = []\n",
                "time_b = []\n",
                "\n",
                "t = 0.0\n",
                "for step in range(max_steps):\n",
                "    t += dt_ctrl\n",
                "    pos = obs_b[0:3]\n",
                "    d_obs = np.linalg.norm(pos - obs_center)\n",
                "\n",
                "    v_des = pid_b.compute(pos, goal_pos, dt=dt_ctrl)\n",
                "    v_safe, h_val, psi_val = cbf_filter.filter(v_des, pos)\n",
                "\n",
                "    traj_b.append(pos.copy())\n",
                "    dists_b.append(d_obs)\n",
                "    h_b.append(h_val)\n",
                "    v_nom_b.append(v_des.copy())\n",
                "    v_cmds_b.append(v_safe.copy())\n",
                "    time_b.append(t)\n",
                "\n",
                "    obs_b, _, terminated, truncated, _ = env_b.step(v_safe)\n",
                "    frames_b.append(env_b.render())\n",
                "\n",
                "    if np.linalg.norm(pos - goal_pos) < 0.06:\n",
                "        break\n",
                "\n",
                "env_b.close()\n",
                "min_dist_b = min(dists_b)\n",
                "min_h_b = min(h_b)\n",
                "print(f\"CBF Filtered Min Distance:          {min_dist_b:.3f} m (Safety Threshold: {D_obs:.2f} m)\")\n",
                "print(f\"CBF Filtered Min Barrier Value h(x): {min_h_b:.3f} (SAFE: h >= 0!)\")\n",
                "\n",
                "# Summary Comparison Table\n",
                "print(\"\\n\" + \"=\"*50)\n",
                "print(\"SAFETY FILTER PERFORMANCE SUMMARY\")\n",
                "print(\"=\"*50)\n",
                "print(f\"  Obstacle Physical Radius:       0.22 m\")\n",
                "print(f\"  CBF Safety Boundary D_obs:      {D_obs:.2f} m\")\n",
                "print(f\"  Unfiltered Min Distance:        {min_dist_a:.3f} m -> Collision: True\")\n",
                "print(f\"  CBF Filtered Min Distance:      {min_dist_b:.3f} m -> Collision: False (SAFE)\")\n",
                "print(f\"  Min Barrier h(x) [Unfiltered]:  {min_h_a:.3f} (< 0)\")\n",
                "print(f\"  Min Barrier h(x) [CBF Filter]:  {min_h_b:.3f} (>= 0)\")\n",
                "print(\"=\"*50)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {"id": "sec8_md"},
            "source": [
                "## 8. Diagnostic Telemetry Plots & Video Playback\n",
                "\n",
                "We visualize the comparative performance across 4 diagnostic panels:\n",
                "1. **3D Spatial Trajectories**: Side-by-side view showing the obstacle sphere, unconstrained path (colliding), and CBF safe path (circumnavigating).\n",
                "2. **Obstacle Distance over Time**: Visualizing the $D_{\\mathrm{obs}}$ boundary line.\n",
                "3. **Barrier Function $h(t)$ over Time**: Demonstrating forward invariance ($h(t) \\ge 0$).\n",
                "4. **Velocity Command Comparison**: Showing nominal $\\mathbf{v}_{\\mathrm{des}}$ vs. filtered $\\mathbf{v}^*$."
            ]
        },
        {
            "cell_type": "code",
            "metadata": {"id": "telemetry_plots"},
            "execution_count": None,
            "outputs": [],
            "source": [
                "traj_a = np.array(traj_a)\n",
                "traj_b = np.array(traj_b)\n",
                "dists_a = np.array(dists_a)\n",
                "dists_b = np.array(dists_b)\n",
                "h_a = np.array(h_a)\n",
                "h_b = np.array(h_b)\n",
                "time_a = np.array(time_a)\n",
                "time_b = np.array(time_b)\n",
                "\n",
                "fig = plt.figure(figsize=(16, 11))\n",
                "\n",
                "# Panel 1: 3D Spatial Trajectories\n",
                "ax1 = fig.add_subplot(2, 2, 1, projection='3d')\n",
                "ax1.plot(traj_a[:, 0], traj_a[:, 1], traj_a[:, 2], 'crimson', lw=2.2, linestyle='--', label='Unfiltered PID (Crash)')\n",
                "ax1.plot(traj_b[:, 0], traj_b[:, 1], traj_b[:, 2], 'teal', lw=2.8, label='CBF Safety Filter (Safe)')\n",
                "\n",
                "# Draw Obstacle Sphere\n",
                "u, v = np.mgrid[0:2*np.pi:25j, 0:np.pi:20j]\n",
                "r_obs = 0.22\n",
                "xs = obs_center[0] + r_obs * np.cos(u) * np.sin(v)\n",
                "ys = obs_center[1] + r_obs * np.sin(u) * np.sin(v)\n",
                "zs = obs_center[2] + r_obs * np.cos(v)\n",
                "ax1.plot_surface(xs, ys, zs, color='red', alpha=0.35, edgecolor='darkred', lw=0.3)\n",
                "\n",
                "# Start and Goal markers\n",
                "ax1.scatter([0.0], [0.0], [1.0], color='green', s=70, label='Start (0,0,1)')\n",
                "ax1.scatter([goal_pos[0]], [goal_pos[1]], [goal_pos[2]], color='gold', s=90, edgecolors='black', label='Goal (1.2,1.2,1.6)')\n",
                "ax1.set_title(\"3D Flight Trajectories: Unfiltered vs. CBF Filter\", fontsize=12, fontweight='bold')\n",
                "ax1.set_xlabel(\"X (m)\")\n",
                "ax1.set_ylabel(\"Y (m)\")\n",
                "ax1.set_zlabel(\"Z (m)\")\n",
                "ax1.legend(loc='upper left')\n",
                "\n",
                "# Panel 2: Distance to Obstacle Center over Time\n",
                "ax2 = fig.add_subplot(2, 2, 2)\n",
                "ax2.plot(time_a, dists_a, 'crimson', lw=2.0, linestyle='--', label='Unfiltered PID')\n",
                "ax2.plot(time_b, dists_b, 'teal', lw=2.2, label='CBF Safety Filter')\n",
                "ax2.axhline(D_obs, color='black', linestyle=':', lw=2.0, label=f'Safety Boundary D_obs ({D_obs}m)')\n",
                "ax2.axhline(0.22, color='red', linestyle='--', lw=1.5, label='Physical Obstacle Surface (0.22m)')\n",
                "ax2.set_title(\"Distance to Obstacle Center ||p - p_obs|| vs. Time\", fontsize=12, fontweight='bold')\n",
                "ax2.set_xlabel(\"Time (s)\")\n",
                "ax2.set_ylabel(\"Distance (m)\")\n",
                "ax2.grid(True, alpha=0.3)\n",
                "ax2.legend(loc='upper right')\n",
                "\n",
                "# Panel 3: Barrier Value h(t) over Time\n",
                "ax3 = fig.add_subplot(2, 2, 3)\n",
                "ax3.plot(time_a, h_a, 'crimson', lw=2.0, linestyle='--', label='h(x) Unfiltered (Violates Safety)')\n",
                "ax3.plot(time_b, h_b, 'teal', lw=2.4, label='h(x) CBF Filter (Forward Invariant)')\n",
                "ax3.axhline(0.0, color='darkgreen', linestyle='-', lw=1.8, label='Safety Boundary h(x) = 0')\n",
                "ax3.fill_between(time_b, 0.0, -0.3, color='red', alpha=0.15, label='Unsafe Zone (h < 0)')\n",
                "ax3.set_title(\"Control Barrier Function h(p) = ||p - p_obs|| - D_obs\", fontsize=12, fontweight='bold')\n",
                "ax3.set_xlabel(\"Time (s)\")\n",
                "ax3.set_ylabel(\"Barrier Value h(x)\")\n",
                "ax3.grid(True, alpha=0.3)\n",
                "ax3.legend(loc='upper right')\n",
                "\n",
                "# Panel 4: Velocity Commands: Nominal vs. Filtered\n",
                "v_nom_b = np.array(v_nom_b)\n",
                "v_cmds_b = np.array(v_cmds_b)\n",
                "ax4 = fig.add_subplot(2, 2, 4)\n",
                "ax4.plot(time_b, np.linalg.norm(v_nom_b, axis=1), 'gray', linestyle='--', label='||v_nominal|| (Desired)')\n",
                "ax4.plot(time_b, np.linalg.norm(v_cmds_b, axis=1), 'teal', lw=2.0, label='||v*|| (CBF Safe Command)')\n",
                "ax4.axhline(1.8, color='black', linestyle=':', label='v_max (1.8 m/s)')\n",
                "ax4.set_title(\"Velocity Magnitudes over Time\", fontsize=12, fontweight='bold')\n",
                "ax4.set_xlabel(\"Time (s)\")\n",
                "ax4.set_ylabel(\"Speed (m/s)\")\n",
                "ax4.grid(True, alpha=0.3)\n",
                "ax4.legend(loc='upper right')\n",
                "\n",
                "plt.tight_layout()\n",
                "plt.show()"
            ]
        },
        {
            "cell_type": "code",
            "metadata": {"id": "display_video"},
            "execution_count": None,
            "outputs": [],
            "source": [
                "# Display In-Notebook Video of CBF Obstacle Avoidance Flight\n",
                "print(\"Displaying CBF-Filtered Autonomous Flight Video (Arena Observer Camera):\")\n",
                "media.show_video(frames_b, fps=30)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {"id": "sec9_md"},
            "source": [
                "## 9. Full Multi-Waypoint Mission with Obstacle Avoidance\n",
                "\n",
                "We now deploy the CBF Safety Filter on the full **5-waypoint tour** from the original tutorial, with an obstacle positioned along the trajectory corridor to prove robust real-time safety during continuous flight."
            ]
        },
        {
            "cell_type": "code",
            "metadata": {"id": "multi_waypoint_cbf"},
            "execution_count": None,
            "outputs": [],
            "source": [
                "# Define 5-Waypoint Route\n",
                "waypoints = [\n",
                "    np.array([ 0.0,  0.0, 1.2], dtype=np.float32),  # Takeoff / Center\n",
                "    np.array([ 1.2,  1.2, 1.6], dtype=np.float32),  # WP 1 (Past obstacle at [0.6, 0.6, 1.35])\n",
                "    np.array([-1.2,  1.2, 1.8], dtype=np.float32),  # WP 2\n",
                "    np.array([-1.2, -1.2, 1.2], dtype=np.float32),  # WP 3\n",
                "    np.array([ 1.2, -1.2, 1.5], dtype=np.float32),  # WP 4\n",
                "    np.array([ 0.0,  0.0, 1.2], dtype=np.float32),  # Return Home Hover\n",
                "]\n",
                "\n",
                "base_env_tour = QuadrotorEnv(target_pos=waypoints[0], camera_name=\"arena_cam\", max_steps=600)\n",
                "env_tour = SingleIntegratorQuadrotorEnv(base_env_tour, v_max=1.8)\n",
                "pid_tour = HighLevelPositionPID(kp=2.2, ki=0.2, kd=0.4, v_max=1.8)\n",
                "cbf_tour = CBFSafetyFilter(obstacles=[obs_center], D_obs=D_obs, alpha=2.5, v_max=1.8)\n",
                "\n",
                "obs, _ = env_tour.reset(seed=42)\n",
                "frames_tour = [env_tour.render()]\n",
                "\n",
                "wp_idx = 0\n",
                "current_target = waypoints[wp_idx]\n",
                "env_tour.set_target_pos(current_target)\n",
                "\n",
                "print(\"--- Executing Multi-Waypoint Mission with CBF Safety Filter ---\")\n",
                "min_d_tour = 999.0\n",
                "\n",
                "for step in range(500):\n",
                "    pos = obs[0:3]\n",
                "    d_obs = np.linalg.norm(pos - obs_center)\n",
                "    if d_obs < min_d_tour:\n",
                "        min_d_tour = d_obs\n",
                "\n",
                "    dist_to_wp = np.linalg.norm(pos - current_target)\n",
                "    if dist_to_wp < 0.18 and wp_idx < len(waypoints) - 1:\n",
                "        wp_idx += 1\n",
                "        current_target = waypoints[wp_idx]\n",
                "        env_tour.set_target_pos(current_target)\n",
                "        print(f\"Step {step:03d}: Reached Waypoint {wp_idx-1}! Transitioning to WP {wp_idx} -> {current_target}\")\n",
                "\n",
                "    v_des = pid_tour.compute(pos, current_target, dt=0.02)\n",
                "    v_safe, _, _ = cbf_tour.filter(v_des, pos)\n",
                "\n",
                "    obs, _, term, trunc, _ = env_tour.step(v_safe)\n",
                "    frames_tour.append(env_tour.render())\n",
                "\n",
                "    if term or trunc:\n",
                "        break\n",
                "\n",
                "env_tour.close()\n",
                "print(f\"\\nMulti-Waypoint Flight Complete!\")\n",
                "print(f\"Minimum Clearance to Obstacle: {min_d_tour:.3f} m (Threshold: {D_obs:.2f} m)\")\n",
                "print(f\"Safety Certified: {min_d_tour >= D_obs}\")\n",
                "\n",
                "print(\"\\nDisplaying Multi-Waypoint Safe Flight Video:\")\n",
                "media.show_video(frames_tour, fps=30)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {"id": "summary_md"},
            "source": [
                "## 10. Summary & Key Takeaways\n",
                "\n",
                "In this tutorial on Control Barrier Functions for quadrotors, you learned:\n",
                "1. **Why Safety Filters are Powerful**: Instead of re-tuning or replacing the goal-reaching PID controller, a CBF Safety Filter minimally intervenes only when safety is threatened.\n",
                "2. **Single-Integrator CBF Math**: How the condition $\\nabla h(\\mathbf{p})^T \\mathbf{v} \\ge -\\alpha h(\\mathbf{p})$ guarantees forward invariance of the safe set $\\mathcal{S}$.\n",
                "3. **Analytical Closed-Form QP Solution**: Because $\\|\\nabla h\\| = 1$, the CBF-QP has an exact, instantaneous solution (Eq. 16 & 19 in `docs/cbf_drone.pdf`) that requires zero third-party QP solvers.\n",
                "4. **Minimally Invasive Operation**: When the drone is far from obstacles or moving away, $\\Psi \\ge 0$, and the filter passes the nominal command through with zero distortion.\n",
                "5. **Physical Realization on 6-DOF Quadrotor**: How the two-tier architecture seamlessly executes safe single-integrator velocity commands on full rigid-body dynamics in MuJoCo."
            ]
        }
    ]
}

if __name__ == "__main__":
    out_path = "/home/aks1/drone_course_repo/tutorials/quadrotor_cbf_safety_filter_colab.ipynb"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=4)
    print(f"Successfully generated new CBF Safety Filter tutorial at: {out_path}")
    print(f"File size: {os.path.getsize(out_path) / 1024:.1f} KB")

