import json
import os
import base64

# Load and encode pipeline diagram to base64 for 100% self-contained offline rendering
img_file_path = "/home/aks1/drone_course_repo/tutorials/single_integrator_pipeline.png"
with open(img_file_path, "rb") as f:
    pipeline_b64 = base64.b64encode(f.read()).decode("utf-8")

img_tag = f"<p align=\"center\"><img src=\"data:image/png;base64,{pipeline_b64}\" width=\"100%\" alt=\"6-DOF Quadrotor Control Pipeline: Single-Integrator Augmented with Black-Box Controller in MuJoCo\" /></p>\n"

notebook = {
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {
        "colab": {
            "provenance": [],
            "authorship_tag": "ABX9TyP...",
            "include_colab_link": True
        },
        "kernelspec": {
            "name": "python3",
            "display_name": "Python 3"
        },
        "language_info": {
            "name": "python"
        },
        "accelerator": "GPU"
    },
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {"id": "header_md"},
            "source": [
                "# 🚁 Perception and Control for Drones: Quadrotor Simulation & Single-Integrator PID Tutorial\n",
                "\n",
                "[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/arunkumar-singh/drone_course_repo/blob/main/tutorials/quadrotor_gym_mujoco_colab.ipynb)\n",
                "\n",
                "Welcome to this hands-on tutorial on simulating and controlling an autonomous **6-DOF Quadrotor** in Google Colab using **Gymnasium**, **MuJoCo**, and **MJX**.\n",
                "\n",
                "### Hierarchical Control Architecture\n",
                "Full quadrotor flight dynamics are complex, underactuated, and non-linear. In practice, robotics engineers use a **two-tier hierarchical control architecture**:\n",
                "\n",
                img_tag,
                "\n",
                "### In This Tutorial, You Will:\n",
                "1. **Install Dependencies**: Set up `gymnasium`, `mujoco`, and `mediapy` in Colab.\n",
                "2. **Define Quadrotor MJCF**: Embed the 6-DOF physics model directly in Python.\n",
                "3. **Build the Gymnasium Environment**: Implement standard `reset()`, `step()`, and `render()`.\n",
                "4. **Black-Box Lower-Level Bridge**: Implement the black-box controller and expose a `SingleIntegratorQuadrotorEnv` wrapper.\n",
                "5. **High-Level Single-Integrator PID**: Derive and implement a 3D position PID controller generating velocity commands.\n",
                "6. **Visual Rollout & In-Colab Video**: Fly through a 3D waypoint mission and view the rendered video directly in Colab.\n",
                "7. **Bonus: Hardware-Accelerated MJX**: Step 1,024 parallel quadrotors on GPU with JAX."
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {"id": "sec1_md"},
            "source": [
                "## 1. Install Dependencies & Configure Headless OpenGL\n",
                "\n",
                "We install `gymnasium`, `mujoco`, and `mediapy` (for in-notebook video playback).\n",
                "\n",
                "> **Note on Headless Rendering in Google Colab**:\n",
                "> Cloud notebooks like Google Colab run without an X11 display server. To enable hardware-accelerated offscreen rendering without OpenGL errors, we configure MuJoCo to use **EGL** (`MUJOCO_GL=\"egl\"`) before initializing the renderer."
            ]
        },
        {
            "cell_type": "code",
            "metadata": {"id": "install_deps"},
            "execution_count": None,
            "outputs": [],
            "source": [
                "# 1. Configure MuJoCo for headless GPU rendering (EGL) in Google Colab\n",
                "import os\n",
                "os.environ[\"MUJOCO_GL\"] = \"egl\"\n",
                "\n",
                "# 2. Install required packages (including mujoco-mjx for GPU simulation)\n",
                "!pip install -q gymnasium mujoco mujoco-mjx mediapy\n",
                "\n",
                "# 3. Ensure EGL GLContext is bound to MuJoCo even in an already-active runtime\n",
                "import mujoco\n",
                "try:\n",
                "    import mujoco.egl\n",
                "    mujoco.GLContext = mujoco.egl.GLContext\n",
                "except Exception:\n",
                "    pass\n",
                "\n",
                "import numpy as np\n",
                "import gymnasium as gym\n",
                "from gymnasium import spaces\n",
                "import mediapy as media\n",
                "\n",
                "print(f\"MuJoCo Version: {mujoco.__version__}\")\n",
                "print(f\"Active OpenGL Platform: {getattr(mujoco, 'GLContext', 'Default')}\")\n",
                "print(f\"Gymnasium Version: {gym.__version__}\")\n",
                "try:\n",
                "    import mujoco.mjx as mjx\n",
                "    print(\"MuJoCo MJX: Available\")\n",
                "except Exception:\n",
                "    print(\"MuJoCo MJX: Not yet loaded\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {"id": "sec2_md"},
            "source": [
                "## 2. Define the Quadrotor Model (MJCF XML)\n",
                "\n",
                "We define the 6-DOF quadrotor in MuJoCo XML format:\n",
                "- **Freejoint root**: Full 6-DOF rigid-body dynamics (3 translation $+ 3$ rotation)\n",
                "- **X-Configuration Arms**: 4 thruster site actuators with counter-rotational yaw torque gears\n",
                "- **Mocap Target Sphere**: Visual golden sphere indicating the current 3D goal waypoint\n",
                "- **Cameras**: Third-person tracking camera (`track_cam`) and stationary wide observer (`arena_cam`)"
            ]
        },
        {
            "cell_type": "code",
            "metadata": {"id": "define_xml"},
            "execution_count": None,
            "outputs": [],
            "source": [
                "QUADROTOR_XML = \"\"\"\n",
                "<mujoco model=\"quadrotor\">\n",
                "  <compiler angle=\"radian\" coordinate=\"local\"/>\n",
                "  <option gravity=\"0 0 -9.81\" integrator=\"RK4\" timestep=\"0.01\"/>\n",
                "\n",
                "  <visual>\n",
                "    <headlight ambient=\"0.4 0.4 0.4\" diffuse=\"0.8 0.8 0.8\" specular=\"0.1 0.1 0.1\"/>\n",
                "    <rgba haze=\"0.15 0.25 0.35 1\"/>\n",
                "    <global azimuth=\"120\" elevation=\"-20\" offwidth=\"1280\" offheight=\"720\"/>\n",
                "  </visual>\n",
                "\n",
                "  <asset>\n",
                "    <texture type=\"skybox\" builtin=\"gradient\" rgb1=\"0.3 0.5 0.7\" rgb2=\"0.0 0.1 0.2\" width=\"512\" height=\"512\"/>\n",
                "    <texture name=\"grid\" type=\"2d\" builtin=\"checker\" width=\"512\" height=\"512\" rgb1=\"0.25 0.35 0.45\" rgb2=\"0.15 0.2 0.25\"/>\n",
                "    <material name=\"grid\" texture=\"grid\" texrepeat=\"2 2\" texuniform=\"true\" reflectance=\"0.2\"/>\n",
                "    <material name=\"chassis\" rgba=\"0.15 0.15 0.15 1.0\" specular=\"0.5\" shininess=\"0.5\"/>\n",
                "    <material name=\"arm\" rgba=\"0.25 0.25 0.25 1.0\"/>\n",
                "    <material name=\"front_prop\" rgba=\"0.95 0.15 0.15 0.85\" specular=\"0.4\"/>\n",
                "    <material name=\"rear_prop\" rgba=\"0.15 0.45 0.95 0.85\" specular=\"0.4\"/>\n",
                "    <material name=\"target_mat\" rgba=\"1.0 0.8 0.0 0.75\" specular=\"0.9\"/>\n",
                "  </asset>\n",
                "\n",
                "  <worldbody>\n",
                "    <light directional=\"true\" diffuse=\"0.8 0.8 0.8\" specular=\"0.3 0.3 0.3\" pos=\"0 0 6.0\" dir=\"0 0 -1\"/>\n",
                "    <light directional=\"true\" diffuse=\"0.4 0.4 0.4\" specular=\"0.1 0.1 0.1\" pos=\"4 -4 5.0\" dir=\"-1 1 -1\"/>\n",
                "    <geom name=\"floor\" type=\"plane\" size=\"12 12 0.1\" material=\"grid\" condim=\"3\"/>\n",
                "\n",
                "    <!-- Target Waypoint Sphere (Mocap Body) -->\n",
                "    <body name=\"target\" pos=\"0.0 0.0 1.0\" mocap=\"true\">\n",
                "      <geom name=\"target_sphere\" type=\"sphere\" size=\"0.08\" material=\"target_mat\" contype=\"0\" conaffinity=\"0\" density=\"0\"/>\n",
                "    </body>\n",
                "\n",
                "    <!-- Observer Cameras -->\n",
                "    <camera name=\"arena_cam\" pos=\"3.8 -3.8 3.0\" xyaxes=\"0.707 0.707 0 -0.408 0.408 0.816\" fovy=\"60\"/>\n",
                "\n",
                "    <!-- 6-DOF Quadrotor Body (mass = 0.500 kg) -->\n",
                "    <body name=\"quadrotor\" pos=\"0 0 0.2\">\n",
                "      <freejoint name=\"root\"/>\n",
                "      <inertial pos=\"0 0 0\" mass=\"0.500\" diaginertia=\"0.0025 0.0025 0.0045\"/>\n",
                "      <camera name=\"track_cam\" mode=\"trackcom\" pos=\"0.0 -3.2 1.6\" xyaxes=\"1 0 0 0 0.45 0.89\" fovy=\"60\"/>\n",
                "\n",
                "      <geom name=\"chassis_geom\" type=\"sphere\" size=\"0.06\" material=\"chassis\" density=\"0\"/>\n",
                "      <geom name=\"arm1\" type=\"capsule\" fromto=\"0.12 0.12 0 -0.12 -0.12 0\" size=\"0.008\" material=\"arm\" density=\"0\"/>\n",
                "      <geom name=\"arm2\" type=\"capsule\" fromto=\"-0.12 0.12 0 0.12 -0.12 0\" size=\"0.008\" material=\"arm\" density=\"0\"/>\n",
                "\n",
                "      <!-- Rotor 0: Front-Right (+x, +y) -->\n",
                "      <geom name=\"motor0\" type=\"cylinder\" pos=\"0.12 0.12 0.015\" size=\"0.015 0.01\" material=\"chassis\" density=\"0\"/>\n",
                "      <geom name=\"prop0\" type=\"cylinder\" pos=\"0.12 0.12 0.025\" size=\"0.06 0.002\" material=\"front_prop\" contype=\"0\" conaffinity=\"0\" density=\"0\"/>\n",
                "      <site name=\"thruster0\" pos=\"0.12 0.12 0.025\"/>\n",
                "\n",
                "      <!-- Rotor 1: Rear-Right (-x, +y) -->\n",
                "      <geom name=\"motor1\" type=\"cylinder\" pos=\"-0.12 0.12 0.015\" size=\"0.015 0.01\" material=\"chassis\" density=\"0\"/>\n",
                "      <geom name=\"prop1\" type=\"cylinder\" pos=\"-0.12 0.12 0.025\" size=\"0.06 0.002\" material=\"rear_prop\" contype=\"0\" conaffinity=\"0\" density=\"0\"/>\n",
                "      <site name=\"thruster1\" pos=\"-0.12 0.12 0.025\"/>\n",
                "\n",
                "      <!-- Rotor 2: Rear-Left (-x, -y) -->\n",
                "      <geom name=\"motor2\" type=\"cylinder\" pos=\"-0.12 -0.12 0.015\" size=\"0.015 0.01\" material=\"chassis\" density=\"0\"/>\n",
                "      <geom name=\"prop2\" type=\"cylinder\" pos=\"-0.12 -0.12 0.025\" size=\"0.06 0.002\" material=\"rear_prop\" contype=\"0\" conaffinity=\"0\" density=\"0\"/>\n",
                "      <site name=\"thruster2\" pos=\"-0.12 -0.12 0.025\"/>\n",
                "\n",
                "      <!-- Rotor 3: Front-Left (+x, -y) -->\n",
                "      <geom name=\"motor3\" type=\"cylinder\" pos=\"0.12 -0.12 0.015\" size=\"0.015 0.01\" material=\"chassis\" density=\"0\"/>\n",
                "      <geom name=\"prop3\" type=\"cylinder\" pos=\"0.12 -0.12 0.025\" size=\"0.06 0.002\" material=\"front_prop\" contype=\"0\" conaffinity=\"0\" density=\"0\"/>\n",
                "      <site name=\"thruster3\" pos=\"0.12 -0.12 0.025\"/>\n",
                "    </body>\n",
                "  </worldbody>\n",
                "\n",
                "  <!-- Actuators: 4 Site Thrusters -->\n",
                "  <actuator>\n",
                "    <general name=\"thrust0\" site=\"thruster0\" gear=\"0 0 1 0 0  0.015\" ctrlrange=\"0 3.0\" ctrllimited=\"true\"/>\n",
                "    <general name=\"thrust1\" site=\"thruster1\" gear=\"0 0 1 0 0 -0.015\" ctrlrange=\"0 3.0\" ctrllimited=\"true\"/>\n",
                "    <general name=\"thrust2\" site=\"thruster2\" gear=\"0 0 1 0 0  0.015\" ctrlrange=\"0 3.0\" ctrllimited=\"true\"/>\n",
                "    <general name=\"thrust3\" site=\"thruster3\" gear=\"0 0 1 0 0 -0.015\" ctrlrange=\"0 3.0\" ctrllimited=\"true\"/>\n",
                "  </actuator>\n",
                "</mujoco>\n",
                "\"\"\"\n",
                "print(\"Quadrotor MJCF definition loaded!\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {"id": "sec3_md"},
            "source": [
                "## 3. Base Gymnasium Environment (`QuadrotorEnv`)\n",
                "\n",
                "The base environment handles the raw MuJoCo physics:\n",
                "- **Action Space**: 4 individual motor thrust inputs in $[-1.0, 1.0]$\n",
                "- **Observation Space**: 12-dim state vector ($[x,y,z]$, $[\\dot{x},\\dot{y},\\dot{z}]$, Euler angles $[\\phi,\\theta,\\psi]$, and body rates $[p,q,r]$)\n",
                "- **Offscreen Rendering**: Built-in `mujoco.Renderer` extracting RGB pixel arrays for video recording"
            ]
        },
        {
            "cell_type": "code",
            "metadata": {"id": "env_class"},
            "execution_count": None,
            "outputs": [],
            "source": [
                "# Ensure headless OpenGL platform (EGL / OSMesa) is active for Colab rendering\n",
                "if \"MUJOCO_GL\" not in os.environ:\n",
                "    os.environ[\"MUJOCO_GL\"] = \"egl\"\n",
                "try:\n",
                "    import mujoco.egl\n",
                "    mujoco.GLContext = mujoco.egl.GLContext\n",
                "except Exception:\n",
                "    try:\n",
                "        import mujoco.osmesa\n",
                "        mujoco.GLContext = mujoco.osmesa.GLContext\n",
                "    except Exception:\n",
                "        pass\n",
                "\n",
                "class QuadrotorEnv(gym.Env):\n",
                "    \"\"\"\n",
                "    Base 6-DOF Quadrotor Gymnasium Environment.\n",
                "    Low-level interface expects 4-motor thrust action commands in [-1.0, 1.0].\n",
                "    \"\"\"\n",
                "    metadata = {\"render_modes\": [\"rgb_array\"], \"render_fps\": 30}\n",
                "\n",
                "    def __init__(\n",
                "        self,\n",
                "        xml_string=QUADROTOR_XML,\n",
                "        target_pos=(0.0, 0.0, 1.0),\n",
                "        dt=0.01,\n",
                "        frame_skip=2,\n",
                "        max_steps=350,\n",
                "        camera_name=\"track_cam\",\n",
                "        render_width=720,\n",
                "        render_height=540,\n",
                "    ):\n",
                "        super().__init__()\n",
                "\n",
                "        self.model = mujoco.MjModel.from_xml_string(xml_string)\n",
                "        self.model.opt.timestep = dt\n",
                "        self.data = mujoco.MjData(self.model)\n",
                "\n",
                "        self.dt = dt\n",
                "        self.frame_skip = frame_skip\n",
                "        self.max_steps = max_steps\n",
                "        self.camera_name = camera_name\n",
                "        self.target_pos = np.array(target_pos, dtype=np.float32)\n",
                "\n",
                "        # Quadrotor Mass & Thrust Parameters\n",
                "        self.body_id = mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_BODY, \"quadrotor\")\n",
                "        self.mass = float(self.model.body_mass[self.body_id])\n",
                "        self.g = 9.81\n",
                "        self.hover_thrust = (self.mass * self.g) / 4.0\n",
                "        self.max_motor_thrust = float(self.model.actuator_ctrlrange[0, 1])\n",
                "\n",
                "        # Low-level Action Space: 4 normalized motor commands\n",
                "        self.action_space = spaces.Box(\n",
                "            low=-1.0, high=1.0, shape=(self.model.nu,), dtype=np.float32\n",
                "        )\n",
                "\n",
                "        # 12-dimensional State Observation Space\n",
                "        high_obs = np.array([\n",
                "            10.0, 10.0, 10.0,     # pos (m)\n",
                "            20.0, 20.0, 20.0,     # vel (m/s)\n",
                "            np.pi, np.pi, np.pi,  # roll, pitch, yaw (rad)\n",
                "            20.0, 20.0, 20.0,     # p, q, r (rad/s)\n",
                "        ], dtype=np.float32)\n",
                "        self.observation_space = spaces.Box(low=-high_obs, high=high_obs, dtype=np.float32)\n",
                "\n",
                "        self.current_step = 0\n",
                "        self.renderer = mujoco.Renderer(self.model, height=render_height, width=render_width)\n",
                "\n",
                "    def set_target_pos(self, target_pos):\n",
                "        \"\"\"Update target waypoint position in physics & visualizer.\"\"\"\n",
                "        self.target_pos = np.array(target_pos, dtype=np.float32)\n",
                "        self.data.mocap_pos[0] = self.target_pos\n",
                "\n",
                "    def _quat_to_euler(self, q):\n",
                "        w, x, y, z = q\n",
                "        sinr_cosp = 2.0 * (w * x + y * z)\n",
                "        cosr_cosp = 1.0 - 2.0 * (x * x + y * y)\n",
                "        roll = np.arctan2(sinr_cosp, cosr_cosp)\n",
                "\n",
                "        sinp = np.clip(2.0 * (w * y - z * x), -1.0, 1.0)\n",
                "        pitch = np.arcsin(sinp)\n",
                "\n",
                "        siny_cosp = 2.0 * (w * z + x * y)\n",
                "        cosy_cosp = 1.0 - 2.0 * (y * y + z * z)\n",
                "        yaw = np.arctan2(siny_cosp, cosy_cosp)\n",
                "        return np.array([roll, pitch, yaw], dtype=np.float32)\n",
                "\n",
                "    def _get_obs(self):\n",
                "        pos = self.data.qpos[0:3].copy()\n",
                "        rpy = self._quat_to_euler(self.data.qpos[3:7])\n",
                "        vel = self.data.qvel[0:3].copy()\n",
                "        omega = self.data.qvel[3:6].copy()\n",
                "        return np.concatenate([pos, vel, rpy, omega]).astype(np.float32)\n",
                "\n",
                "    def _get_info(self):\n",
                "        pos = self.data.qpos[0:3]\n",
                "        dist = np.linalg.norm(pos - self.target_pos)\n",
                "        return {\"step\": self.current_step, \"dist_to_target\": float(dist), \"altitude\": float(pos[2])}\n",
                "\n",
                "    def reset(self, seed=None, options=None):\n",
                "        super().reset(seed=seed)\n",
                "        mujoco.mj_resetData(self.model, self.data)\n",
                "        self.data.mocap_pos[0] = self.target_pos\n",
                "\n",
                "        self.data.qpos[0:3] = [0.0, 0.0, 0.2]\n",
                "        self.data.qpos[3:7] = [1.0, 0.0, 0.0, 0.0]\n",
                "        self.data.qvel[:] = 0.0\n",
                "        mujoco.mj_forward(self.model, self.data)\n",
                "\n",
                "        self.current_step = 0\n",
                "        return self._get_obs(), self._get_info()\n",
                "\n",
                "    def step(self, action):\n",
                "        self.current_step += 1\n",
                "\n",
                "        action = np.clip(action, -1.0, 1.0)\n",
                "        thrusts = (action + 1.0) * 0.5 * self.max_motor_thrust\n",
                "        self.data.ctrl[:] = thrusts\n",
                "\n",
                "        for _ in range(self.frame_skip):\n",
                "            mujoco.mj_step(self.model, self.data)\n",
                "\n",
                "        obs = self._get_obs()\n",
                "        pos, vel, rpy = obs[0:3], obs[3:6], obs[6:9]\n",
                "\n",
                "        pos_error = np.linalg.norm(pos - self.target_pos)\n",
                "        reward = float(1.0 / (1.0 + pos_error) - 0.1 * np.linalg.norm(vel) - 0.2 * np.linalg.norm(rpy[0:2]))\n",
                "\n",
                "        crashed = pos[2] < 0.05 or abs(rpy[0]) > np.deg2rad(70) or abs(rpy[1]) > np.deg2rad(70)\n",
                "        out_of_bounds = np.any(np.abs(pos[0:2]) > 6.0) or pos[2] > 6.0\n",
                "        terminated = bool(crashed or out_of_bounds)\n",
                "        truncated = bool(self.current_step >= self.max_steps)\n",
                "\n",
                "        return obs, reward, terminated, truncated, self._get_info()\n",
                "\n",
                "    def render(self, camera_name=None):\n",
                "        cam = camera_name if camera_name is not None else self.camera_name\n",
                "        self.renderer.update_scene(self.data, camera=cam)\n",
                "        return self.renderer.render()\n",
                "\n",
                "    def close(self):\n",
                "        if self.renderer is not None:\n",
                "            self.renderer.close()\n",
                "            self.renderer = None\n",
                "\n",
                "print(\"Base QuadrotorEnv created!\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {"id": "sec4_md"},
            "source": [
                "## 4. The Single-Integrator Abstraction & \"Black-Box\" Lower-Level Bridge\n",
                "\n",
                "### Hierarchical Control Pipeline Architecture\n",
                "The diagram below illustrates the complete 3-tier control flow with dual feedback loops:\n",
                "\n",
                img_tag,
                "\n",
                "\n",
                "### The Single-Integrator Dynamics Model\n",
                "To simplify planning, guidance, and high-level control, we abstract the 6-DOF quadrotor as a **single integrator system**:\n",
                "$$\\dot{\\mathbf{p}}(t) = \\mathbf{v}_{\\text{cmd}}(t)$$\n",
                "where $\\mathbf{p} = [x, y, z]^T \\in \\mathbb{R}^3$ is position, and the control input chosen by our high-level controller is a **3D velocity command**:\n",
                "$$\\mathbf{u}_{\\text{high}} = \\mathbf{v}_{\\text{cmd}} = [v_{x,\\text{cmd}}, v_{y,\\text{cmd}}, v_{z,\\text{cmd}}]^T$$\n",
                "\n",
                "### The \"Black-Box\" Lower-Level Controller (`BlackBoxLowLevelController`)\n",
                "Sitting directly between the high-level velocity commands and MuJoCo's 4 motor actuators is the **black-box controller**. It automatically handles all complex aerodynamics and flight dynamics:\n",
                "1. **Velocity Tracking**: Computes desired body accelerations from velocity errors: $\\mathbf{a}_{\\text{cmd}} = K_v (\\mathbf{v}_{\\text{cmd}} - \\mathbf{v})$\n",
                "2. **Heading & Tilt Kinematics**: Maps horizontal accelerations to roll ($\\phi_{\\text{des}}$) and pitch ($\\theta_{\\text{des}}$) angles in the quadrotor's body heading frame\n",
                "3. **Tilt Compensation**: Scales collective thrust by $\\frac{1}{\\cos\\phi \\cos\\theta}$ so the drone does not drop altitude when banking\n",
                "4. **Motor Allocation Mixer Inversion**: Inverts the physical mixer matrix to produce individual motor commands $[T_0, T_1, T_2, T_3]$\n",
                "\n",
                "We wrap the base environment using `SingleIntegratorQuadrotorEnv(gym.Wrapper)`, which **exposes the 3D velocity command directly as the Gym action space**!"
            ]
        },
        {
            "cell_type": "code",
            "metadata": {"id": "display_pipeline_img"},
            "execution_count": None,
            "outputs": [],
            "source": [
                "# Display Pipeline Architecture Diagram\n",
                "from IPython.display import Image, display\n",
                "import os\n",
                "\n",
                "img_candidates = [\n",
                "    \"single_integrator_pipeline.png\",\n",
                "    \"tutorials/single_integrator_pipeline.png\",\n",
                "    \"/home/aks1/drone_course_repo/tutorials/single_integrator_pipeline.png\",\n",
                "]\n",
                "img_found = next((p for p in img_candidates if os.path.exists(p)), None)\n",
                "\n",
                "if img_found:\n",
                "    display(Image(img_found, width=950))\n",
                "else:\n",
                "    display(Image(\"https://raw.githubusercontent.com/arunkumar-singh/drone_course_repo/main/tutorials/single_integrator_pipeline.png\", width=950))"
            ]
        },
        {
            "cell_type": "code",
            "metadata": {"id": "blackbox_controller"},
            "execution_count": None,
            "outputs": [],
            "source": [
                "class BlackBoxLowLevelController:\n",
                "    \"\"\"\n",
                "    Black-Box Lower-Level Flight Controller.\n",
                "    Bridges high-level 3D velocity commands v_cmd to MuJoCo 4-rotor thrust actuators.\n",
                "    \"\"\"\n",
                "    def __init__(self, mass=0.500, g=9.81, max_thrust=3.0, d=0.12, c_tau=0.015):\n",
                "        self.mass = mass\n",
                "        self.g = g\n",
                "        self.max_thrust = max_thrust\n",
                "        self.d = d\n",
                "        self.c_tau = c_tau\n",
                "\n",
                "    def compute_motor_action(self, v_cmd, obs):\n",
                "        \"\"\"\n",
                "        Takes high-level velocity command v_cmd = [vx, vy, vz] and current state obs.\n",
                "        Returns normalized 4-motor action in [-1.0, 1.0] for MuJoCo.\n",
                "        \"\"\"\n",
                "        pos, vel = obs[0:3], obs[3:6]\n",
                "        roll, pitch, yaw = obs[6:9]\n",
                "        p, q, r = obs[9:12]\n",
                "\n",
                "        # 1. Desired accelerations from velocity tracking\n",
                "        ax_world = 3.2 * (v_cmd[0] - vel[0])\n",
                "        ay_world = 3.2 * (v_cmd[1] - vel[1])\n",
                "        az_cmd   = 6.0 * (v_cmd[2] - vel[2])\n",
                "\n",
                "        # 2. Heading rotation into quadrotor yaw frame\n",
                "        cy, sy = np.cos(yaw), np.sin(yaw)\n",
                "        ax_body =  cy * ax_world + sy * ay_world\n",
                "        ay_body = -sy * ax_world + cy * ay_world\n",
                "\n",
                "        # Tilt angle kinematics\n",
                "        pitch_des = np.clip(ax_body / self.g, -0.25, 0.25)\n",
                "        roll_des  = np.clip(-ay_body / self.g, -0.25, 0.25)\n",
                "\n",
                "        # 3. Attitude stabilization torques\n",
                "        tau_x = 0.075 * (roll_des - roll) - 0.015 * p\n",
                "        tau_y = 0.075 * (pitch_des - pitch) - 0.015 * q\n",
                "        tau_z = 0.020 * (0.0 - yaw) - 0.005 * r\n",
                "\n",
                "        # 4. Collective thrust with tilt compensation\n",
                "        tilt_comp = np.clip(np.cos(roll) * np.cos(pitch), 0.65, 1.0)\n",
                "        total_thrust = np.clip(self.mass * (self.g + az_cmd) / tilt_comp, 0.1 * self.mass * self.g, 1.9 * self.mass * self.g)\n",
                "\n",
                "        # 5. Exact analytical inverse allocation mixer\n",
                "        inv_4d = 1.0 / (4.0 * self.d)\n",
                "        inv_4c = 1.0 / (4.0 * self.c_tau)\n",
                "        base = total_thrust / 4.0\n",
                "\n",
                "        t0 = base + inv_4d * tau_x - inv_4d * tau_y + inv_4c * tau_z\n",
                "        t1 = base + inv_4d * tau_x + inv_4d * tau_y - inv_4c * tau_z\n",
                "        t2 = base - inv_4d * tau_x + inv_4d * tau_y + inv_4c * tau_z\n",
                "        t3 = base - inv_4d * tau_x - inv_4d * tau_y - inv_4c * tau_z\n",
                "\n",
                "        thrusts = np.clip([t0, t1, t2, t3], 0.0, self.max_thrust)\n",
                "        return ((thrusts / (0.5 * self.max_thrust)) - 1.0).astype(np.float32)\n",
                "\n",
                "\n",
                "class SingleIntegratorQuadrotorEnv(gym.Wrapper):\n",
                "    \"\"\"\n",
                "    Gymnasium Wrapper exposing a Single-Integrator Interface: ṗ = v_cmd.\n",
                "    Action Space: 3D Velocity Command [vx, vy, vz] in m/s.\n",
                "    \"\"\"\n",
                "    def __init__(self, env, v_max=2.0):\n",
                "        super().__init__(env)\n",
                "        self.v_max = v_max\n",
                "        # Action space is now a 3D velocity command in m/s!\n",
                "        self.action_space = spaces.Box(low=-v_max, high=v_max, shape=(3,), dtype=np.float32)\n",
                "        self.black_box = BlackBoxLowLevelController(\n",
                "            mass=env.mass, max_thrust=env.max_motor_thrust\n",
                "        )\n",
                "\n",
                "    def step(self, v_cmd):\n",
                "        # 1. Retrieve current observation\n",
                "        current_obs = self.env._get_obs()\n",
                "        v_cmd_clipped = np.clip(v_cmd, -self.v_max, self.v_max)\n",
                "\n",
                "        # 2. Black-box controller generates low-level 4-motor commands\n",
                "        motor_action = self.black_box.compute_motor_action(v_cmd_clipped, current_obs)\n",
                "\n",
                "        # 3. Step raw MuJoCo environment\n",
                "        return self.env.step(motor_action)\n",
                "\n",
                "    def set_target_pos(self, target_pos):\n",
                "        \"\"\"Forward target waypoint updates to inner environment.\"\"\"\n",
                "        self.env.set_target_pos(target_pos)\n",
                "\n",
                "print(\"BlackBoxLowLevelController and SingleIntegratorQuadrotorEnv ready!\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {"id": "sec5_md"},
            "source": [
                "## 5. High-Level Single-Integrator PID Controller\n",
                "\n",
                "Now we implement the **High-Level Position PID Controller**.\n",
                "\n",
                "### Mathematical Derivation\n",
                "For a single-integrator system $\\dot{\\mathbf{p}} = \\mathbf{v}_{\\text{cmd}}$, let position error be:\n",
                "$$\\mathbf{e}(t) = \\mathbf{p}_{\\text{target}}(t) - \\mathbf{p}(t)$$\n",
                "\n",
                "The high-level PID control law calculates the 3D velocity command as:\n",
                "$$\\mathbf{v}_{\\text{cmd}}(t) = K_p \\mathbf{e}(t) + K_i \\int_0^t \\mathbf{e}(\\tau)\\,d\\tau + K_d \\frac{d\\mathbf{e}(t)}{dt}$$\n",
                "\n",
                "### Closed-Loop Dynamics\n",
                "Substituting $\\dot{\\mathbf{p}} = \\mathbf{v}_{\\text{cmd}}$ into the error dynamics:\n",
                "$$\\dot{\\mathbf{e}} = \\dot{\\mathbf{p}}_{\\text{target}} - \\mathbf{v}_{\\text{cmd}}$$\n",
                "For stationary waypoints ($\\dot{\\mathbf{p}}_{\\text{target}} = 0$):\n",
                "$$\\dot{\\mathbf{e}} + K_p \\mathbf{e} + K_i \\int \\mathbf{e}\\,d\\tau + K_d \\dot{\\mathbf{e}} = 0$$\n",
                "- **Proportional Gain ($K_p$)**: Acts as a virtual spring pulling the drone toward the target waypoint with convergence rate $\\tau = 1/K_p$.\n",
                "- **Integral Gain ($K_i$)**: Eliminates steady-state positioning error.\n",
                "- **Derivative Gain ($K_d$)**: Acts as damping to prevent velocity overshoot."
            ]
        },
        {
            "cell_type": "code",
            "metadata": {"id": "highlevel_pid"},
            "execution_count": None,
            "outputs": [],
            "source": [
                "class HighLevelPositionPID:\n",
                "    \"\"\"\n",
                "    High-Level 3D Position PID Controller assuming Single-Integrator Dynamics (ṗ = v_cmd).\n",
                "    Computes velocity commands [vx, vy, vz] to navigate to target waypoints.\n",
                "    \"\"\"\n",
                "    def __init__(self, kp=2.2, ki=0.3, kd=0.4, v_max=1.8):\n",
                "        self.kp = kp\n",
                "        self.ki = ki\n",
                "        self.kd = kd\n",
                "        self.v_max = v_max\n",
                "        self.integral = np.zeros(3, dtype=np.float32)\n",
                "        self.prev_error = np.zeros(3, dtype=np.float32)\n",
                "\n",
                "    def reset(self):\n",
                "        self.integral = np.zeros(3, dtype=np.float32)\n",
                "        self.prev_error = np.zeros(3, dtype=np.float32)\n",
                "\n",
                "    def compute(self, current_pos, target_pos, dt=0.02):\n",
                "        \"\"\"\n",
                "        Computes 3D velocity command v_cmd from current position and target waypoint.\n",
                "        \"\"\"\n",
                "        error = np.array(target_pos, dtype=np.float32) - np.array(current_pos, dtype=np.float32)\n",
                "\n",
                "        # Conditional anti-windup integration\n",
                "        if np.linalg.norm(error) < 0.6:\n",
                "            self.integral = np.clip(self.integral + error * dt, -0.5, 0.5)\n",
                "\n",
                "        # Derivative of error\n",
                "        derivative = (error - self.prev_error) / dt\n",
                "        self.prev_error = error.copy()\n",
                "\n",
                "        # PID Velocity Command Law\n",
                "        v_cmd = self.kp * error + self.ki * self.integral + self.kd * derivative\n",
                "\n",
                "        # Velocity magnitude saturation limit\n",
                "        speed = np.linalg.norm(v_cmd)\n",
                "        if speed > self.v_max:\n",
                "            v_cmd = v_cmd * (self.v_max / speed)\n",
                "\n",
                "        return v_cmd.astype(np.float32)\n",
                "\n",
                "print(\"HighLevelPositionPID controller implemented!\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {"id": "sec6_md"},
            "source": [
                "## 6. End-to-End Simulation Rollout & In-Colab Video Playback\n",
                "\n",
                "Notice how clean and intuitive the interaction loop becomes:\n",
                "```python\n",
                "# 1. High-level PID computes 3D velocity command\n",
                "v_cmd = pid.compute(pos, current_target, dt=0.02)\n",
                "\n",
                "# 2. Step the Gymnasium environment directly with the velocity command!\n",
                "obs, reward, terminated, truncated, info = env.step(v_cmd)\n",
                "```\n",
                "\n",
                "Let's execute a 3D multi-waypoint flight patrol and render the video directly inside Colab!"
            ]
        },
        {
            "cell_type": "code",
            "metadata": {"id": "run_sim_video"},
            "execution_count": None,
            "outputs": [],
            "source": [
                "# 1. Define 3D Multi-Waypoint Route\n",
                "waypoints = [\n",
                "    np.array([ 0.0,  0.0, 1.2]),  # Takeoff / Center\n",
                "    np.array([ 1.2,  1.2, 1.6]),  # Waypoint 1 (Front-Right)\n",
                "    np.array([-1.2,  1.2, 1.8]),  # Waypoint 2 (Rear-Right)\n",
                "    np.array([-1.2, -1.2, 1.2]),  # Waypoint 3 (Rear-Left)\n",
                "    np.array([ 1.2, -1.2, 1.5]),  # Waypoint 4 (Front-Left)\n",
                "    np.array([ 0.0,  0.0, 1.2]),  # Home Hover\n",
                "]\n",
                "\n",
                "# 2. Instantiate Base Environment and wrap with Single-Integrator Interface\n",
                "base_env = QuadrotorEnv(target_pos=waypoints[0], camera_name=\"track_cam\")\n",
                "env = SingleIntegratorQuadrotorEnv(base_env, v_max=1.8)\n",
                "\n",
                "print(f\"Wrapped Action Space:      {env.action_space} (3D Velocity Commands [vx, vy, vz])\")\n",
                "print(f\"Wrapped Observation Space: {env.observation_space}\")\n",
                "\n",
                "# 3. Instantiate High-Level PID\n",
                "pid = HighLevelPositionPID(kp=2.2, ki=0.3, kd=0.4, v_max=1.8)\n",
                "\n",
                "obs, info = env.reset(seed=42)\n",
                "frames = [env.render()]\n",
                "\n",
                "wp_idx = 0\n",
                "current_target = waypoints[wp_idx]\n",
                "env.set_target_pos(current_target)\n",
                "dwell_steps = 0\n",
                "\n",
                "print(\"\\n--- Executing Autonomous Multi-Waypoint Flight ---\")\n",
                "for step in range(1, 350):\n",
                "    pos = obs[0:3]\n",
                "    dist = np.linalg.norm(pos - current_target)\n",
                "\n",
                "    # Waypoint Transition Logic: converge < 18cm and hold for 10 steps\n",
                "    if dist < 0.18:\n",
                "        dwell_steps += 1\n",
                "        if dwell_steps > 10 and wp_idx < len(waypoints) - 1:\n",
                "            wp_idx += 1\n",
                "            current_target = waypoints[wp_idx]\n",
                "            env.set_target_pos(current_target)\n",
                "            dwell_steps = 0\n",
                "            print(f\"--> [Step {step:03d}] Reached Waypoint! New Target WP{wp_idx}: {current_target}\")\n",
                "    else:\n",
                "        dwell_steps = 0\n",
                "\n",
                "    # 1. High-Level PID computes velocity command\n",
                "    v_cmd = pid.compute(current_pos=pos, target_pos=current_target, dt=0.02)\n",
                "\n",
                "    # 2. Step environment directly with v_cmd!\n",
                "    # Black-box controller translates v_cmd -> 4-motor thrusts -> MuJoCo\n",
                "    obs, reward, terminated, truncated, info = env.step(v_cmd)\n",
                "\n",
                "    # 3. Capture camera frame from MuJoCo Visualizer\n",
                "    frames.append(env.render())\n",
                "\n",
                "    if step % 50 == 0:\n",
                "        print(f\"Step {step:03d} | Pos: [{pos[0]:5.2f}, {pos[1]:5.2f}, {pos[2]:5.2f}] | v_cmd: [{v_cmd[0]:5.2f}, {v_cmd[1]:5.2f}, {v_cmd[2]:5.2f}] | Error: {dist*100:5.1f} cm\")\n",
                "\n",
                "    if terminated or truncated:\n",
                "        break\n",
                "\n",
                "env.close()\n",
                "print(f\"\\nFlight Tour Finished! Total frames captured: {len(frames)}\")\n",
                "\n",
                "# 4. Display Simulation Video inline inside Colab\n",
                "print(\"Displaying Simulation Video:\")\n",
                "try:\n",
                "    media.show_video(frames, fps=30)\n",
                "except Exception as e:\n",
                "    print(f\"Video preview note: {e} (In Google Colab, media.show_video displays the interactive video player inline!)\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {"id": "sec7_md"},
            "source": [
                "## 7. Bonus: Parallel Simulation on GPU with MuJoCo MJX\n",
                "\n",
                "**MuJoCo MJX** provides hardware-accelerated (GPU/TPU) parallel physics in JAX.\n",
                "Instead of running a single environment sequentially on the CPU, MJX allows you to step **thousands of quadrotors in parallel** using `jax.vmap`."
            ]
        },
        {
            "cell_type": "code",
            "metadata": {"id": "mjx_demo"},
            "execution_count": None,
            "outputs": [],
            "source": [
                "# 0. Ensure mujoco-mjx is installed and importable\n",
                "try:\n",
                "    from mujoco import mjx\n",
                "except (ImportError, ModuleNotFoundError):\n",
                "    import sys, subprocess\n",
                "    print(\"Installing mujoco-mjx for GPU acceleration...\")\n",
                "    subprocess.check_call([sys.executable, \"-m\", \"pip\", \"install\", \"-q\", \"mujoco-mjx\"])\n",
                "    from mujoco import mjx\n",
                "\n",
                "import jax\n",
                "import jax.numpy as jnp\n",
                "\n",
                "# 1. Convert MuJoCo Model to MJX\n",
                "mj_model = mujoco.MjModel.from_xml_string(QUADROTOR_XML)\n",
                "mjx_model = mjx.put_model(mj_model)\n",
                "mjx_data = mjx.put_data(mj_model, mujoco.MjData(mj_model))\n",
                "\n",
                "print(f\"JAX Default Backend: {jax.default_backend()}\")\n",
                "print(f\"Available Devices:   {jax.devices()}\")\n",
                "\n",
                "# 2. Define JIT-compiled single-environment step function\n",
                "@jax.jit\n",
                "def mjx_step_fn(m, d, ctrl):\n",
                "    d = d.replace(ctrl=ctrl)\n",
                "    return mjx.step(m, d)\n",
                "\n",
                "# 3. Vectorize across N parallel environments with jax.vmap\n",
                "N_ENVS = 1024\n",
                "batched_step = jax.jit(jax.vmap(mjx_step_fn, in_axes=(None, 0, 0)))\n",
                "\n",
                "# Initialize 1,024 parallel states\n",
                "batch_data = jax.vmap(lambda _: mjx_data)(jnp.arange(N_ENVS))\n",
                "\n",
                "# Generate random motor inputs for all 1,024 drones\n",
                "key = jax.random.PRNGKey(0)\n",
                "batch_ctrl = jax.random.uniform(key, shape=(N_ENVS, mj_model.nu), minval=0.0, maxval=3.0)\n",
                "\n",
                "# Execute parallel step\n",
                "batch_data_next = batched_step(mjx_model, batch_data, batch_ctrl)\n",
                "\n",
                "print(f\"Stepped {N_ENVS} parallel quadrotor environments in one GPU pass!\")\n",
                "print(f\"Batch qpos tensor shape: {batch_data_next.qpos.shape}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {"id": "summary_md"},
            "source": [
                "## Summary\n",
                "\n",
                "In this tutorial, you learned:\n",
                "1. How to define and load a 6-DOF quadrotor model in **MuJoCo**\n",
                "2. The **single-integrator abstraction** ($\\dot{\\mathbf{p}} = \\mathbf{v}_{\\text{cmd}}$) for quadrotor navigation\n",
                "3. How to build a **black-box lower-level controller** that bridges high-level velocity commands with raw 4-motor actuators\n",
                "4. How to implement and tune a **High-Level Position PID Controller** interacting with Gymnasium\n",
                "5. How to render and display HD simulation videos inline using **MediaPy**\n",
                "6. How to scale to massive parallel simulation on GPU using **MuJoCo MJX**"
            ]
        }
    ]
}

out_path = "/home/aks1/drone_course_repo/tutorials/quadrotor_gym_mujoco_colab.ipynb"
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2)

print(f"Successfully generated updated Colab tutorial at: {out_path}")
print(f"File size: {os.path.getsize(out_path)/1024:.1f} KB")
